apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webbff-lightblue-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: pod-webbff
      labels:
        app: webbff
    spec:
      containers:
        - name: webbff
          image: "registry.ng.bluemix.net/vbudiusibmcom/webbff:latest"
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: webbff-lightblue-service
  labels:
    app: webbff
spec:
  type: NodePort
  selector:
    app: webbff
  ports:
   - protocol: TCP
     port: 3001
     nodePort: 30120
