# Server configuration
server:
  context-path:
  port: 8085

# Spring properties
spring:
  application:
     name: auth-microservice
     cloudant:
        username: 14bea0d8-8434-49be-a1db-82d2c4aab312-bluemix
        password: 4709b1e9f01bbf5b5ed8d691c3908beef20427e5685af9d8a12eec192e16064f
        host: 14bea0d8-8434-49be-a1db-82d2c4aab312-bluemix.cloudant.com
        port: 443
        database: customers

