---
swagger: "2.0"
info:
  x-ibm-name: "order"
  title: "order"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/api"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
  apic-oauth-provider:
    type: "oauth2"
    description: ""
    flow: "implicit"
    authorizationUrl: "https://api.us.apiconnect.ibmcloud.com/vbudiusibmcom-dev/bluecompute-vbudiusibmcom/oauth20/authorize"
    scopes:
      blue: "bluecompute scope"
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
security:
- clientIdHeader: []
  apic-oauth-provider:
  - "blue"
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - gatewayscript:
        title: "gatewayscript"
        version: "1.0.0"
        source: "var path = apim.getvariable('request.path');\napim.setvariable('real-path', path);\nvar uid = apim.getvariable('oauth.resource-owner');\napim.setvariable('message.headers.ibm-app-user', uid);"
    - invoke:
        target-url: "$(TARGET_HOST)$(real-path)"
    catch: []
  phase: "realized"
  properties:
    TARGET_HOST:
      value: "http://web-bff-vbudiusibmcom.mybluemix.net"
      description: ""
      encoded: false
paths:
  /orders/{id}:
    get:
      responses:
        200:
          description: "200 OK"
          schema:
            $ref: "#/definitions/order"
      description: "Get my order by ID"
    parameters:
    - name: "id"
      type: "integer"
      required: true
      in: "path"
      format: "int32"
  /orders:
    get:
      responses:
        200:
          description: "200 OK"
          schema:
            $ref: "#/definitions/order_array"
      security:
      - clientIdHeader: []
        apic-oauth-provider:
        - "blue"
      description: "Get all my orders"
    post:
      responses:
        200:
          description: "200 OK"
          schema:
            type: object
      parameters:
      - name: "order"
        required: true
        in: "body"
        schema:
          $ref: "#/definitions/order"
      description: "Create an order"
definitions:
  order_array:
    type: "array"
    items:
      $ref: "#/definitions/order"
  order:
    properties:
      orderId:
        type: "integer"
        format: "int64"
      count:
        type: "integer"
        format: "int32"
      customerId:
        type: "string"
      itemId:
        type: "integer"
        format: "int32"
    additionalProperties: false
tags: []
